In [ ]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
-1:-10

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

In [ ]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

In [ ]:
-5.23:6

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

In [ ]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
x=2
seq(1, x,x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [ ]:
x=50
seq(0, x,x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

In [ ]:
x = c(9,8,7,6)
ind = seq(along=x)
ind

[1] 1 2 3 4

In [ ]:
x[ ind[2] ]

[1] 8

In [ ]:
Sys.time()

[1] "2026-09-03 04:09:27 UTC"

In [ ]:
Sys.Date()

[1] "2026-09-03"

In [ ]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by ="years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [ ]:
seq(as.Date("2017-01-01") , by = "months" , length =6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

In [ ]:
startdate = as.Date("2016-1-1")
enddate = as.Date("2017-1-1")

out = seq(enddate ,startdate,by ="-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

In [ ]:
letters[1:3]
letters[21:23]

[1] "a" "b" "c"

[1] "u" "v" "w"

In [ ]:
LETTERS[3:1]

[1] "C" "B" "A"

In [ ]:
rep(3.5, times=10)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

In [ ]:
rep(1:4, each = 2,times=3)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [ ]:
ans = seq(from=2 , to=8, by=2)
ans

[1] 2 4 6 8

In [ ]:
x = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
rep(x,3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

In [ ]:
rep(2, length.out=5)

[1] 2 2 2 2 2

In [ ]:
rep(c("a","b","c"),length=2)

[1] "a" "b"

In [ ]:
y = c(9,8,5,7,6)
y
order(y)

[1] 9 8 5 7 6

[1] 3 5 4 2 1

In [ ]:
order(y, decreasing = TRUE)

[1] 1 2 4 5 3

In [ ]:
mode(2.432)
mode("India")

[1] "numeric"

[1] "character"

In [ ]:
mode(data.frame(x=1:2, y=c("India", "USA")))

[1] "list"

In [ ]:
mode(print)

[1] "function"

In [ ]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)
x1
x2
x1+x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [ ]:
x1[2,1] = "hello"
x1

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

In [ ]:
matlist = list(x1,x2)
matlist

[[1]]
     [,1]    [,2]
[1,] "1"     "2"
[2,] "hello" "4"

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1 = list(c("water" , "juice" , "lemonade"), rep(1:4, each=2), matrix(data=5:8,nrow=2,ncol=2,byrow=T))
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1[[1]]
z1[1][2]

[1] "water"    "juice"    "lemonade"

[[1]]
NULL

In [ ]:
z1[[1]][2]

[1] "juice"